// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class fbees
{
        public const string achievement_endless_champion = "CgkItvun2fwCEAIQCA"; // <GPGSID>
        public const string achievement_endless_fan = "CgkItvun2fwCEAIQBw"; // <GPGSID>
        public const string leaderboard_endless_maximum_points = "CgkItvun2fwCEAIQAQ"; // <GPGSID>
        public const string achievement_try_endless = "CgkItvun2fwCEAIQBg"; // <GPGSID>
        public const string achievement_bee_family = "CgkItvun2fwCEAIQCQ"; // <GPGSID>
        public const string achievement_hardworking_bee = "CgkItvun2fwCEAIQBA"; // <GPGSID>
        public const string achievement_champion_bee = "CgkItvun2fwCEAIQBQ"; // <GPGSID>
        public const string achievement_nice_bee = "CgkItvun2fwCEAIQAw"; // <GPGSID>
        public const string leaderboard_levels_complete = "CgkItvun2fwCEAIQAg"; // <GPGSID>
        public const string leaderboard_endless_length = "CgkItvun2fwCEAIQCg"; // <GPGSID>

}

